In [1]:
from pathlib import Path
from io import StringIO

import pandas as pd

current_path = Path.cwd()
project_root = current_path if (current_path / "requirements.txt").exists() else current_path.parent
data_dir = project_root / "data"
output_csv_path = data_dir / "sample_cleaned.csv"

print("pandas_version:", pd.__version__)
print("project_root:", project_root)
print("data_dir_exists:", data_dir.exists())
print("output_csv_path:", output_csv_path)

pandas_version: 2.0.3
project_root: /Users/im-youngchan/Desktop/US Financial
data_dir_exists: True
output_csv_path: /Users/im-youngchan/Desktop/US Financial/data/sample_cleaned.csv

In [2]:
sample_csv_text = """company_name,ticker,sector,revenue_usd_m,operating_income_usd_m,net_income_usd_m,planned_data_checks,include_in_research,unit,frequency,source_note
Apple Inc.,APPL,consumer technology,1000,300,250,3,True,USD million,annual_sample,class_sample
Microsoft Corporation,MSFT,software and cloud,900,320,260,3,True,USD million,annual_sample,class_sample
NVIDIA Corporation,NVDA,semiconductor,700,280,220,3,True,USD million,annual_sample,class_sample
Sample Corporation,TEST,practice only,100,10,5,1,False,USD million,annual_sample,class_sample
"""

raw_df = pd.read_csv(StringIO(sample_csv_text))

print("raw_row_count:", len(raw_df))
print("raw_column_count:", len(raw_df.columns))
raw_df

raw_row_count: 4
raw_column_count: 11

,company_name,ticker,sector,revenue_usd_m,operating_income_usd_m,net_income_usd_m,planned_data_checks,include_in_research,unit,frequency,source_note
0,Apple Inc.,APPL,consumer technology,1000,300,250,3,True,USD million,annual_sample,class_sample
1,Microsoft Corporation,MSFT,software and cloud,900,320,260,3,True,USD million,annual_sample,class_sample
2,NVIDIA Corporation,NVDA,semiconductor,700,280,220,3,True,USD million,annual_sample,class_sample
3,Sample Corporation,TEST,practice only,100,10,5,1,False,USD million,annual_sample,class_sample

In [3]:
print("columns:")
print(list(raw_df.columns))

columns:
['company_name', 'ticker', 'sector', 'revenue_usd_m', 'operating_income_usd_m', 'net_income_usd_m', 'planned_data_checks', 'include_in_research', 'unit', 'frequency', 'source_note']

In [4]:
basic_columns = ["company_name", "ticker", "revenue_usd_m"]
basic_df = raw_df[basic_columns]

basic_df

            company_name ticker  revenue_usd_m
0             Apple Inc.   APPL           1000
1  Microsoft Corporation   MSFT            900
2     NVIDIA Corporation   NVDA            700
3     Sample Corporation   TEST            100

In [5]:
include_mask = raw_df["include_in_research"] == True
research_df = raw_df[include_mask]

print("research_row_count:", len(research_df))
print("research_ticker_list:", list(research_df["ticker"]))
research_df

research_row_count: 3
research_ticker_list: ['APPL', 'MSFT', 'NVDA']

,company_name,ticker,sector,revenue_usd_m,operating_income_usd_m,net_income_usd_m,planned_data_checks,include_in_research,unit,frequency,source_note
0,Apple Inc.,APPL,consumer technology,1000,300,250,3,True,USD million,annual_sample,class_sample
1,Microsoft Corporation,MSFT,software and cloud,900,320,260,3,True,USD million,annual_sample,class_sample
2,NVIDIA Corporation,NVDA,semiconductor,700,280,220,3,True,USD million,annual_sample,class_sample

In [6]:
clean_columns = [
    "company_name",
    "ticker",
    "sector",
    "revenue_usd_m",
    "operating_income_usd_m",
    "net_income_usd_m",
    "unit",
    "frequency",
    "source_note",
]

cleaned_df = raw_df.loc[include_mask, clean_columns].copy()

print("cleaned_row_count:", len(cleaned_df))
print("cleaned_column_count:", len(cleaned_df.columns))
cleaned_df

cleaned_row_count: 3
cleaned_column_count: 9

,company_name,ticker,sector,revenue_usd_m,operating_income_usd_m,net_income_usd_m,unit,frequency,source_note
0,Apple Inc.,APPL,consumer technology,1000,300,250,USD million,annual_sample,class_sample
1,Microsoft Corporation,MSFT,software and cloud,900,320,260,USD million,annual_sample,class_sample
2,NVIDIA Corporation,NVDA,semiconductor,700,280,220,USD million,annual_sample,class_sample

In [7]:
if not data_dir.exists():
    raise FileNotFoundError("data 폴더가 없습니다. 프로젝트 루트에 data 폴더를 만든 뒤 다시 실행하세요.")

cleaned_df.to_csv(output_csv_path, index=False)

print("saved_csv_path:", output_csv_path)
print("saved_csv_exists:", output_csv_path.exists())

saved_csv_path: /Users/im-youngchan/Desktop/US Financial/data/sample_cleaned.csv
saved_csv_exists: True

In [8]:
saved_df = pd.read_csv(output_csv_path)

print("saved_row_count:", len(saved_df))
print("saved_column_count:", len(saved_df.columns))
print("saved_ticker_list:", list(saved_df["ticker"]))
saved_df

saved_row_count: 3
saved_column_count: 9
saved_ticker_list: ['APPL', 'MSFT', 'NVDA']

,company_name,ticker,sector,revenue_usd_m,operating_income_usd_m,net_income_usd_m,unit,frequency,source_note
0,Apple Inc.,APPL,consumer technology,1000,300,250,USD million,annual_sample,class_sample
1,Microsoft Corporation,MSFT,software and cloud,900,320,260,USD million,annual_sample,class_sample
2,NVIDIA Corporation,NVDA,semiconductor,700,280,220,USD million,annual_sample,class_sample

In [9]:
large_revenue_df = saved_df[saved_df["revenue_usd_m"] >= 800]

print("large_revenue_row_count:", len(large_revenue_df))
large_revenue_df[["ticker", "revenue_usd_m"]]

large_revenue_row_count: 2

  ticker  revenue_usd_m
0   APPL           1000
1   MSFT            900